services:
  redis:
    image: redis:7-alpine
    container_name: rasengan-chat-demo-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - rasengan-chat-demo-network
    command: redis-server --appendonly yes

volumes:
  redis_data:
    driver: local

networks:
  rasengan-chat-demo-network:
    driver: bridge