import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import type { RasenganServerConfig } from '../config/index.js';

/**
 * Start the production server from built output.
 *
 * Spawns the generated entry file (`index.js`) with the appropriate
 * runtime (Node.js or Bun), forwarding signals for graceful shutdown.
 * The entry file is expected to have been generated by `rasengan-server build`.
 *
 * @param config - Server configuration (port, host, preset, build options).
 */
export async function start(config: RasenganServerConfig): Promise<void> {
  const outDir = resolve(config.build?.outDir || 'dist');
  const entry = join(outDir, 'index.js');

  const port = config.port ?? process.env.PORT ?? 3000;
  const host = config.host ?? process.env.HOST ?? '0.0.0.0';

  // Update config with environment variables
  const updatedConfig = {
    ...config,
    port: Number(port),
    host: host,
  };

  if (!existsSync(entry)) {
    console.error(
      `\n  [rasengan-server] No built output found at ${entry}\n` +
        `  Run \`rasengan-server build\` first.\n`
    );
    process.exit(1);
  }

  const preset = config.preset ?? 'node';

  // RFC-0010: .env* is already loaded into process.env by cli.ts's
  // main() before this function is even called — the `env` object built
  // from `process.env` further down just forwards what's already there.

  if (preset === 'workerd') {
    console.error(
      `\n  [rasengan-server] Workerd does not support direct server start.\n` +
        `  Use \`wrangler deploy\` to publish the output, or run the generated\n` +
        `  entry with a workerd-compatible runtime (e.g. \`miniflare\`).\n`
    );
    process.exit(1);
  }

  const env = {
    ...process.env,
    NODE_ENV: 'production',
    RASENGAN_SERVER_CONFIG: JSON.stringify(updatedConfig),
    // Tells the spawned server (utils/log-server-info.ts) that THIS
    // process already owns Ctrl+C — see RASENGAN_SERVER_DEV_MANAGED
    // doc comment there for why the server must not also grab it.
    RASENGAN_SERVER_DEV_MANAGED: '1',
  };

  let child: ChildProcess | null = null;

  if (preset === 'bun') {
    child = spawn('bun', ['run', entry], {
      stdio: 'inherit',
      env,
    });
  } else {
    child = spawn('node', [entry], {
      stdio: 'inherit',
      env,
    });
  }

  child.on('exit', (code) => {
    process.exit(code ?? 0);
  });

  child.on('error', (err) => {
    console.error(
      `\n  [rasengan-server] Failed to start server: ${err.message}\n`
    );
    process.exit(1);
  });

  const onSignal = (signal: NodeJS.Signals) => {
    console.log('\n[rasengan-server] Stopping prod server...');
    if (child && !child.killed) {
      child.kill(signal);
    }
  };

  process.on('SIGINT', () => onSignal('SIGINT'));
  process.on('SIGTERM', () => onSignal('SIGTERM'));
}
