import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import type { RasenganServerConfig } from '../config/index.js';

/**
 * Start the production server from built output.
 *
 * Spawns the generated entry file (`index.js`) with the appropriate
 * runtime (Node.js or Bun), forwarding signals for graceful shutdown.
 * The entry file is expected to have been generated by `rasengan-server build`.
 *
 * @param config - Server configuration (port, host, preset, build options).
 */
export async function start(config: RasenganServerConfig): Promise<void> {
  const outDir = resolve(config.build?.outDir || 'dist');
  const entry = join(outDir, 'index.js');

  if (!existsSync(entry)) {
    console.error(
      `\n  [rasengan-server] No built output found at ${entry}\n` +
        `  Run \`rasengan-server build\` first.\n`
    );
    process.exit(1);
  }

  const preset = config.preset ?? 'node';

  if (preset === 'workerd') {
    console.error(
      `\n  [rasengan-server] Workerd does not support direct server start.\n` +
        `  Use \`wrangler deploy\` to publish the output, or run the generated\n` +
        `  entry with a workerd-compatible runtime (e.g. \`miniflare\`).\n`
    );
    process.exit(1);
  }

  const env = {
    ...process.env,
    NODE_ENV: 'production',
    RASENGAN_SERVER_PORT: String(config.port ?? 3000),
    RASENGAN_SERVER_HOST: config.host ?? '0.0.0.0',
  };

  let child: ChildProcess | null = null;

  if (preset === 'bun') {
    child = spawn('bun', ['run', entry], {
      stdio: 'inherit',
      env,
    });
  } else {
    child = spawn('node', [entry], {
      stdio: 'inherit',
      env,
    });
  }

  child.on('exit', (code) => {
    process.exit(code ?? 0);
  });

  child.on('error', (err) => {
    console.error(
      `\n  [rasengan-server] Failed to start server: ${err.message}\n`
    );
    process.exit(1);
  });

  const onSignal = (signal: NodeJS.Signals) => {
    if (child && !child.killed) {
      child.kill(signal);
    }
  };

  process.on('SIGINT', () => onSignal('SIGINT'));
  process.on('SIGTERM', () => onSignal('SIGTERM'));
}
